name: Generate profile summary cards

on:
  schedule:
    - cron: "0 1 * * *" # daily 01:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Umer-Farooq-CS
          UTC_OFFSET: 5
          BRANCH_NAME: output
          AUTO_PUSH: "true"

